default: &default
  adapter: postgresql
  encoding: unicode
  username: 'azhir'
  password: 1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: az_economy_development

test:
  <<: *default
  database: az_economy_test

production:
  <<: *default
  database: az_economy_production
